name = "nottedeiricercatori-unight"
compatibility_date = "2026-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "notte-ricercatori"
database_id = "8ff4737e-9848-453e-9e80-1298ce0f1057"